using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


using Jackie_s_WordList;

namespace Jackie_Wordmaker
{
    public static class PreMadeList
    {
        public static void Premade(int type, WordList wl)
        {
            switch (type)
            {
                case 0:
                    wl.addWord("prodigal", "exceedingly or recklessly wasteful");
                    wl.addWord("prosaic", "consisting or characteristic of prose; matter-of-fact; straight forward / dull, lack of imagination");
                    wl.addWord("pugnacious", "combative, quick to fight");
                    wl.addWord("quell", "to ease; to calm down");
                    wl.addWord("quixotic", "foolishly idealistic; extravagantly chivalrous");
                    wl.addWord("raconteur", "known for telling witty stories and anecdotes");
                    wl.addWord("raucous", "loud and harsh");
                    wl.addWord("ravenous", "very hungry");
                    wl.addWord("raze", "to demolish; flatten to the ground level");
                    wl.addWord("rebuff", "to refuse someone; to reject an offer");
                    wl.addWord("rebuke", "to criticize sharply");
                    wl.addWord("rectitude", "conduct according to moral principles");
                    wl.addWord("redolent", "aromatic; fragnant, suggestive");
                    wl.addWord("relinquish", "to surrender or release");
                    wl.addWord("reprehensible", "deserving to be severely criticized");
                    wl.addWord("repugnant", "offensive, very distateful, repulsive");
                    wl.addWord("resilient", "to bounce back from adversity or change");
                    wl.addWord("respite", "temporary relief");
                    wl.addWord("sardonic", "bitterly sneering; mocking; sarcastic");
                    wl.addWord("savor", "(verb) to taste or smell, esp. with pleasure/ (noun) the taste or smell");
                    wl.addWord("sedentary", "sitting down most of the time");
                    wl.addWord("sedition", "the promotion of rebellion against the government");
                    wl.addWord("serene", "calm and peaceful");
                    wl.addWord("solicitous", "showing ancious concern");
                    wl.addWord("soporific", "promoting sleep");
                    wl.addWord("sporadic", "occuring irregularly");
                    wl.addWord("squander", "to spend wastefully");
                    wl.addWord("stalwart", "strong, bold, daring, firm, and resolute; having determination and a stick-to-it attitude");
                    wl.addWord("stymie", "to obstruct; to stump");
                    wl.addWord("substantiate", "to support with evidence");
                    wl.addWord("subtle", "not immediately obvious; hard to understand");
                    wl.addWord("supplant", "to take the place of");
                    wl.addWord("temerity", "reckless disregard for danger or one's own safety; recklessness");
                    wl.addWord("temperate", "inconsistent, moderate; without extremes");
                    wl.addWord("tenuous", "weak; thin");
                    wl.addWord("thwart", "to prevent or frustrate");
                    wl.addWord("tirade", "an abusive speech");
                    wl.addWord("tranquil", "calm, unruffled");
                    wl.addWord("transitory", "short-lived; temporary; only passing, not permanent");
                    wl.addWord("trivial", "of little worth or importance");
                    wl.addWord("truculent", "tending to argue and disagree, often vehemently and with great noise and commotion");
                    wl.addWord("uncouth", "crude and unrefined; awkward, clumpsy, and/or ungraceful");
                    wl.addWord("unremitting", "never slackening or getting any less or any easier; persistence");
                    wl.addWord("vacillate", "to move back and forth, especially being unable to make up one's mind");
                    wl.addWord("vacuous", "lacking substance or intelligence");
                    wl.addWord("variegated", "distinctly marked with different colors; diverse");
                    wl.addWord("venal", "capable of being bribed or corrupted");
                    wl.addWord("venerate", "to look upon with respect and honor");
                    wl.addWord("viable", "able to live; capable of success");
                    wl.addWord("vicarious", "felt as if one were taking part in the experiences of another");
                    wl.addWord("vigilant", "alert and watchful, esp. for what is dangerous");
                    wl.addWord("virtuos", "one with great skill, esp. in music or the arts");
                    wl.addWord("virulent", "extremely infectious or harmful; bitterly hostile");
                    wl.addWord("vociferous", "offensively loud and often given to demonstration of agitated emotions or agitated outcry");
                    wl.addWord("voracious", "devouring; extremely hungry");
                    wl.addWord("wan", "sickly pale; colorless");
                    wl.addWord("watershed", "a critical point that marks a division");
                    wl.addWord("whimsical", "not able to be predicted; constantly changing");
                    wl.addWord("abash", "to confuse or distress; to cause perplexity and uncertainty; to embarass");
                    wl.addWord("abdicate", "to willin give up the position of king, queen, etc; to choose not to fulfill a role or duty");
                    wl.addWord("accolade", "an award or honor; a sign of great respect");
                    wl.addWord("accord", "agreement");
                    wl.addWord("acoustics", "science of sound; quality that makes a room easy or hard to hear in");
                    wl.addWord("acquiesce", "to agree without protest");
                    wl.addWord("acquit", "to declare free of guilt; to clear of charges");
                    wl.addWord("acrid", "harsh; sarcastic; bitter and pungent in taste or odor");
                    wl.addWord("acumen", "keenness of mind; good insight; quickness; accuracy; mental sharpness");
                    wl.addWord("adamant", "stubbornly unyielding; impervious to please, appeal");
                    wl.addWord("admonish", "to warn so a fault can be corrected or danger avoided");
                    wl.addWord("adroit", "clever or skillfull in using the hands or mind");
                    wl.addWord("adversity", "difficulties; misfortune");
                    wl.addWord("aggregate", "total");
                    wl.addWord("alacrity", "cheerful willingness; swiftness");
                    wl.addWord("alias", "an assumption of a false name or pseudonym");
                    wl.addWord("lurid", "caushing shock or horror; tastelessly vivid; glowing like fire through a haze");
                    wl.addWord("malicious", "to cause pain, injury, or distress to another");
                    wl.addWord("martinet", "one who is strict in discipline, and enjoy authority too much");
                    wl.addWord("maverick", "one who rebels; a nonconformist; an individualist");
                    wl.addWord("mercenary", "motivated only by monetary or personal gain");
                    wl.addWord("mercurial", "easily changeable; erratic");
                    wl.addWord("metaphor", "a figure of speech calling one thing another to imply likeness");
                    wl.addWord("misanthrope", "one who hates or mistrusts mankind");
                    wl.addWord("modicum", "a small. very modest, or token amount");
                    wl.addWord("mundane", "typical of this world; commonplace");
                    wl.addWord("myriad", "an indefinitely large number");
                    wl.addWord("naive", "simple; childlike; lacking worldly wisdom");
                    wl.addWord("negligible", "of little value or importance");
                    wl.addWord("neophyte", "a recent convert; a novice or beginner");
                    wl.addWord("nonchalant", "seemingly to be unconcerned or indifferent");
                    wl.addWord("nostalgia", "a general longing for the past or to return home");
                    wl.addWord("obscure", "lacking light; dim; dark");
                    wl.addWord("obsolete", "no longer working or in use; out of date");
                    wl.addWord("obstreperous", "noisy and boisterous; sometime even agressive or defiant");
                    wl.addWord("opportunist", "one who takes advantage of every opportunity, whether or not it is moral to do so");
                    wl.addWord("opulence", "extreme wealth; luxuriousness; abundance");
                    wl.addWord("ornate", "highly, often excessively decorated");
                    wl.addWord("palatable", "pleasant or acceptable to the taste");
                    wl.addWord("panegyric", "a formal public compliment or elaborated praise");
                    wl.addWord("paramount", "supreme; ranking higher than others in power or importance");
                    wl.addWord("parochial", "restricted; limited; narrow; local");
                    wl.addWord("patronize", "to sponsor or support; to be kind or helpful in a snobbish way, as if dealing with an inferior");
                    wl.addWord("penchant", "a strong liking");
                    wl.addWord("penurious", "unwilling to spend or spare any money / unyielding, unprofitable / poverty-stricken");
                    wl.addWord("perfunctory", "done without care or interest or merely as a form of routine");
                    wl.addWord("pertinent", "relevant");
                    wl.addWord("phlegmatic", "having a calm, sluggish temperament; unemotional");
                    wl.addWord("plethora", "an excessive amount");
                    wl.addWord("poignant", "important, moving; often emotionally significant");
                    wl.addWord("portentous", "significant, usually in a threatening or omnious way; filled with heavy misgiving");
                    wl.addWord("preclude", "to make impossible; to prevent the occurrence of");
                    wl.addWord("predatory", "characterized by robbing or exploiting others; living by capturing and feeding on other animal");
                    wl.addWord("frugal", "costing or spending little; sparing in cost or expenditure");
                    wl.addWord("furtive", "sneaky");
                    wl.addWord("gingerly", "very carefully; cautiously");
                    wl.addWord("haughty", "being overwhelmingly proud, vain, and self-centered");
                    wl.addWord("hiatus", "an interruption in activity or progress");
                    wl.addWord("hyperbole", "exaggeration");
                    wl.addWord("iconoclast", "one who attacks and seeks to destroy widely accepted ideas");
                    wl.addWord("immutable", "unchangeable");
                    wl.addWord("impassioned", "filled with emotion; fervent");
                    wl.addWord("impetus", "an impending or originating force");
                    wl.addWord("implacable", "unable to be pacified; relentless");
                    wl.addWord("improvise", "to do without preparation");
                    wl.addWord("impugn", "to challenge the accuracy or honesty of something");
                    wl.addWord("inane", "lacking sense, substance, or logic");
                    wl.addWord("incipient", "keen or penetrating in thought or expression");
                    wl.addWord("incoherent", "not sticking together; not logically connected");
                    wl.addWord("indigent", "poor; needy; destitute");
                    wl.addWord("indignant", "filled with indignation (anger aroused by something unjust, mean, or unworthy)");
                    wl.addWord("indolent", "exhausted and lacking energy");
                    wl.addWord("ineffable", "incapable of being expressed");
                    wl.addWord("innovative", "marked by a new or unusual way of doing things");
                    wl.addWord("inscrutable", "hard to understand; enigmatic");
                    wl.addWord("insular", "narrow in outlook; provincial");
                    wl.addWord("insuperable", "impossible to overcome");
                    wl.addWord("intransigent", "refusing to compromise or agree");
                    wl.addWord("inundate", "to flood");
                    wl.addWord("itinerant", "travelling from place to place, esp. for work");
                    wl.addWord("jocular", "characterized by joking; given to joking");
                    wl.addWord("judicious", "having sound and prudent judgement");
                    wl.addWord("languid", "sluggish; lacking energy");
                    wl.addWord("lavish", "generous; extravagant");
                    wl.addWord("lethargic", "dull; sluggish; moving slowly");
                    wl.addWord("levity", "lack of seriousness; esp. when improper");
                    wl.addWord("limpid", "clear and clean; without blemish or confusion");
                    wl.addWord("listless", "having no interest in what is going on about one; languid; spiritless");
                    wl.addWord("lugubrious", "sad or mournful, esp. in a way that seems exaggerated or ridiculous");
                    wl.addWord("decorum", "polite behavior");
                    wl.addWord("decry", "to speak out against strongly and openly");
                    wl.addWord("demagogue", "a leader who obtains power by appealing to the emotions and passions of the people");
                    wl.addWord("deprecate", "to belittle,; express of disapproval; deplore");
                    wl.addWord("depreciate", "to reduce in price or value");
                    wl.addWord("despondent", "so sad");
                    wl.addWord("diatribe", "prolonged and bitter speech or writing");
                    wl.addWord("digress", "to turn aside from the main subject");
                    wl.addWord("dilettante", "one who engages an art with only superficial skill; an amateur");
                    wl.addWord("diligent", "painstaking and steady");
                    wl.addWord("din", "disorder and noise; tumult and confusion");
                    wl.addWord("dirge", "a song or hymn of grief, a lamentation");
                    wl.addWord("divisive", "creating conflict");
                    wl.addWord("docile", "easy to teach; submissive");
                    wl.addWord("dubious", "causing doubt; questionable");
                    wl.addWord("duplicitous", "given to or marked by deliberate deceptiveness in behavior or speech");
                    wl.addWord("eccentric", "unconventional; odd");
                    wl.addWord("eclipse", "to overshadow");
                    wl.addWord("egalitarian", "of the belief that all people should have equal rights");
                    wl.addWord("elucidate", "to make something clear; to clarify");
                    wl.addWord("embellish", "to decorate; to add ornamental or fictitious details to");
                    wl.addWord("eminent", "outstanding, distinguished, towering above others");
                    wl.addWord("enervate", "to weaken");
                    wl.addWord("equivocal", "capable of multiple interpretations; unclear");
                    wl.addWord("erratic", "inconsistent, unpredictable");
                    wl.addWord("erudite", "well-educated");
                    wl.addWord("esoteric", "known by or confined to a small number of people");
                    wl.addWord("euphemism", "the substitution of an agreeable word or phrase to replace one that might offend");
                    wl.addWord("euphony", "please sound, esp. of words");
                    wl.addWord("exasperate", "to make very important; to annoy greatly");
                    wl.addWord("exculpate", "to clear from blame or guilty");
                    wl.addWord("exemplary", "worthy to serve as a model");
                    wl.addWord("expedient", "(adj) helping one's self-interest / (nou) a means to an end");
                    wl.addWord("expunge", "to erase; to eliminate completely");
                    wl.addWord("extravagant", "excessive, unrestrained");
                    wl.addWord("extricate", "to remove from an entanglement or difficulty");
                    wl.addWord("fawn", "to exhibit affection like a dog; to flatter excessively");
                    wl.addWord("altruistic", "unselfish; benevolent; caring more for others than oneself");
                    wl.addWord("amicable", "pleasant, friendly");
                    wl.addWord("animosity", "bitter hostility, esp. that which provokes punitive action");
                    wl.addWord("anomaly", "a departure from the regular pattern");
                    wl.addWord("antediluvian", "extremely old; usually, historically a reference to era before the flood");
                    wl.addWord("antipathy", "a feeling or strong repulsion or aversion");
                    wl.addWord("arcane", "understood only by a few");
                    wl.addWord("archaic", "characteristic of a much earlier period  no longer current or applicable");
                    wl.addWord("arid", "dry and barren; not interesting");
                    wl.addWord("ascetic", "self-denying");
                    wl.addWord("auspicious", "marked by favorable circumstances");
                    wl.addWord("avarice", "excessive desire for wealth");
                    wl.addWord("benefactor", "one who helps and supports others");
                    wl.addWord("benign", "kindly; creating a favorable influence; (in medicine) not dangerous to one's health");
                    wl.addWord("berate", "to scold angrily and at length");
                    wl.addWord("bolster", "to support or strengthen");
                    wl.addWord("bombastic", "pretentious, inflated speech or writing, lacking in humility");
                    wl.addWord("brevity", "briefness");
                    wl.addWord("brusque", "abrupt and curt of manner");
                    wl.addWord("candor", "frankness or sincerity of expression");
                    wl.addWord("caustic", "capable of burning or corroding by chemical action; biting sarcastic, cutting");
                    wl.addWord("charlatan", "a fake; one who pretends to have expert knowledge");
                    wl.addWord("chicanery", "deception by trickery");
                    wl.addWord("circuitous", "being or taking a roundabout, lengthy course");
                    wl.addWord("coerce", "to force by threat or intimidation");
                    wl.addWord("colloquial", "appropriate to spoken, as opposed to written language; informal");
                    wl.addWord("complement", "something that completes a whole or brings to perfection");
                    wl.addWord("conjecture", "an inference or conclusion based on incomplete evidence");
                    wl.addWord("consensus", "a general agreement, common consent");
                    wl.addWord("contemptuous", "manifesting or displaying strong dislike, scorn, or contempt");
                    wl.addWord("contiguous", "sharing a common boundary; adjoining");
                    wl.addWord("copious", "containing or yielding plenty; bountiful in amount or manner");
                    wl.addWord("cordial", "warm, sincere, friendly, and gracious");
                    wl.addWord("corroborate", "to strengthen; confirm; support");
                    wl.addWord("cosmopolitan", "having worldwide scope; so sophisticated as to be at home in all parts of the world");
                    wl.addWord("covert", "concealed or disguised; not openly practiced");
                    wl.addWord("cryptic", "secretive or partially concealed; mysterious");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    wl.addWord("", "");
                    
                    break;

                case 1:
                    wl.addWord("Sepulchre", " a burial vault, a receptable built for sacred relics");
                    wl.addWord("Utopia", "Ideally perfect place, especially in its social, political, and moral aspects");
                    wl.addWord("Edifice", "A building, especially one of imposing appearance or size");
                    wl.addWord("Physiognomy", "the art of judging human character from facial features");
                    wl.addWord("Heterodox", "Not in agreement with accepted beliefs, esoecially in church doctrine or dogma");
                    wl.addWord("Infamy", "Evil fame or reputation");
                    wl.addWord("Autumnal", "A period of maturity verging on decline");
                    wl.addWord("Ignominy", "A great personal dishonor or humiliation");
                    wl.addWord("Deportment", "a manner of personal conduct; behavior");
                    wl.addWord("Countenance", "appearance, especially the expression of the face");
                    wl.addWord("Phantasmagoric", "a fantastic sequence of haphazardly associative imagery, as seen in dreams or fever");
                    wl.addWord("Visage", "the face or facial expression of a person");
                    wl.addWord("Iniquity", "gross immorality or injustice; wickedness");
                    wl.addWord("tremulous", "marked by trembling, quivering or shaking");
                    wl.addWord("sagamores", "subordinate chief among the Algonquians of North America");
                    wl.addWord("Preemptory", "to take the place of; displace, to have precedence or predominance over");
                    wl.addWord("Paramour", "a lover, especially one in an adulterous relationship");
                    wl.addWord("vivify", "to give or bring life to; animate");
                    wl.addWord("penitence", "remorse for past conduct, regret for wrongdoing");
                    wl.addWord("ascetic", "a person who renounces material comforts and leads a life of austere self-discipline, especially as an act of religious devotion");
                    wl.addWord("Reviled", "to assail with abusive language");
                    wl.addWord("Exhortation", "a speech or discourse that encourages, incites, or earnestly advises");
                    wl.addWord("Amenable", "Responsive to advice, authority, or suggestion; responsible to higher authority");
                    wl.addWord("Caprice", "an impulsive change of mind");
                    wl.addWord("Ludicrous", "ridiculous, laughable because of obvious absurdity");
                    wl.addWord("Intrinsic", "of or relating to the essential nature of a thing; inherent");
                    wl.addWord("sagacity", "the quality of being discerning, sound in judgment and farsighted,; wisdom");
                    wl.addWord("Somniferous", "inducing sleep");
                    wl.addWord("Askance", "with disapproval, suspicion, or distrust");
                    wl.addWord("Diabolical", "having devilish qualities or characteristics");
                    wl.addWord("Vindicate", "to clear of accusion, defend or justify");
                    wl.addWord("Mountebank", "hawker of quack medicines who attracts customers with stories, jokes, or tricks");
                    wl.addWord("inauspicious", "ill-fated, omnious");
                    wl.addWord("Magistrate", "a civil officer with power to administer and enforce law");
                    wl.addWord("Solemnity", "Somberness");
                    wl.addWord("malefactress", "(feminine of malefactor), evil doer, one who commits crime");
                    wl.addWord("Impropriety", "the quality or condition of being improper");
                    wl.addWord("Evanescent", "vanishing like a vapor");
                    wl.addWord("Beadle", "a minor parish official");
                    wl.addWord("Papist", "a disapproving term for a Roman Catholic");
                    wl.addWord("Pillory", "a wooden framework on a post, with holes for the head and hands, in which offenders were formerly locked to be exposed to public scorn as punishment");
                    wl.addWord("Alchemy", "a medieval chemical philosophy having as its asserted aims the transmutation of base metals into gold, the discovery of the panacea, and the preparation of the elixir of longevity");
                    wl.addWord("Expostulation", "to reason earnestly with someone in an effort to dissuade or correct");
                    wl.addWord("Preternatural", "exceeding the ordinary, unusual extraodinary");
                    wl.addWord("Flank", "to put something on each side of");
                    wl.addWord("Tankard", "a large drinking cup having a single handle and often a hinged cover, espcially a tall pewter or silver mug");
                    wl.addWord("Panopoly", "a splendid or striking array");
                    wl.addWord("Exigencies", "a pressing or urgent situation");
                    wl.addWord("Eldritch", "strange or unearthly, eerie");
                    wl.addWord("Benevolence", "an inclination to perform kind, charitable acts");
                    wl.addWord("Catechism", "a book giving a brief summary of the basic principles of Christianity in question-and-answer form");
                    wl.addWord("Indefeasible", "that cannot be annuled or void");
                    wl.addWord("Sundering", "Breaking into parts");
                    wl.addWord("Appellation", "a name, title, or designation");
                    wl.addWord("Apothecary", "One that prepares and sells drugs and other medicines; a pharmacist");
                    wl.addWord("Parochial", "of relating to, supported by, or located in a parish");
                    wl.addWord("Despondent", "feeling dejected");
                    wl.addWord("Erudition", "deep, extensive learning");
                    wl.addWord("Commodiousness", "Spacious, roomy");
                    wl.addWord("Emaciated", "to be extremely thin, as in starvation");
                    wl.addWord("Efficacious", "producing or capable of producing a desired effect");
                    wl.addWord("Scourge", "whip used to inflict punishment");
                    break;

            }
        }
    }
}
